### ISSUE TITLE
ミスです

### ISSUE THREAD

**Issue by tk330** [fullness-java2021/spring-text#10]

**Comment by fullness-java2021** [comment]
Helperクラスは`form`パッケージの中に入れてもよいですし、別途`helper`パッケージを作ってそこに入れてもよいですよ。

**Comment by tk330** [comment]
送信するissueのグループを間違えてしまいました、申し訳ありません。

仕様書にない新しいパッケージを作ってもよいということであれば、可読性のためにhelperパッケージを作ることにします。
コメントありがとうございました。
