### ISSUE TITLE
ログイン画面で正しい入力値を入れてもログインできない

### ISSUE THREAD

**Issue by tk330** [fullness-java2021/spring-text#9]
データベースへの登録は確認済みです。
チーム1で協力して解決していますが難航しているので見ていただきたいです

![ログイン - Google Chrome 2021-06-08 16 23 20](https://user-images.githubusercontent.com/82434649/121141611-235e2280-c876-11eb-87eb-8033297223cb.png)

**Comment by fullness-java2021** [comment]
このエラーメッセージを見ると、ログイン画面（`login.html`）のinputタグのname属性か、SpringSecurityのユーザ名を指定している箇所が`username`になっていない可能性がるので確認してみてください。

**Comment by tk330** [comment]
チームで解決しました。

**Comment by tk330** [comment]
返信ありがとうございます。
xmのSQL文のlのusernameを囲む記号についてミスがあり、解決しました。

**Comment by fullness-java2021** [comment]
了解です！
